.PHONY: clean All

All:
	@echo "----------Building project:[ dicionarioED - Debug ]----------"
	@cd "dicionarioED" && "$(MAKE)" -f  "dicionarioED.mk"
clean:
	@echo "----------Cleaning project:[ dicionarioED - Debug ]----------"
	@cd "dicionarioED" && "$(MAKE)" -f  "dicionarioED.mk" clean
